/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * セッション作成
         * @description 新しいマーダーミステリーのセッションを作成し、AIがシナリオを生成する
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/phase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在のフェーズ情報取得
         * @description セッションの現在のフェーズ情報を取得する。プレイヤーごとに異なる情報が返される。
         */
        get: operations["getPhase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/phase/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * フェーズを進める
         * @description 次のフェーズに進む。セッションオーナーのみ実行可能。
         */
        post: operations["advancePhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 投票
         * @description 投票フェーズで犯人だと思うプレイヤーに投票する
         */
        post: operations["vote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ゲーム結果取得
         * @description ゲームの真相、投票結果、勝者を取得する
         */
        get: operations["getResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateSessionRequest: {
            /**
             * @description プレイヤー人数
             * @example 3
             */
            playerCount: number;
            /**
             * @description 難易度
             * @example easy
             * @enum {string}
             */
            difficulty: "easy" | "medium" | "hard";
        };
        CreateSessionResponse: {
            /**
             * @description セッションID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            sessionId: string;
            /**
             * @description セッションオーナーのプレイヤーID
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            ownerPlayerId: string;
            /**
             * @description 全プレイヤーのID
             * @example [
             *       "660e8400-e29b-41d4-a716-446655440001",
             *       "660e8400-e29b-41d4-a716-446655440002",
             *       "660e8400-e29b-41d4-a716-446655440003"
             *     ]
             */
            playerIds: string[];
            initialPhase: components["schemas"]["PhaseInfo"];
        };
        PhaseInfo: {
            /**
             * @description フェーズ番号
             * @example 0
             */
            phaseNumber: number;
            /**
             * @description フェーズの種類
             * @example introduction
             * @enum {string}
             */
            phaseType: "introduction" | "discussion" | "investigation" | "voting" | "reveal";
            /**
             * @description フェーズの説明
             * @example 事件の概要と各自の立場を確認
             */
            description: string;
            /**
             * @description 全プレイヤーに公開される情報
             * @example 被害者：サミュエル・ゴールドスタイン（65歳）...
             */
            publicText: string;
            /**
             * @description 推奨プレイ時間（分）
             * @example 10
             */
            duration: number;
        };
        PhaseResponse: {
            /**
             * @description フェーズ番号
             * @example 0
             */
            phaseNumber: number;
            /**
             * @description フェーズの種類
             * @example introduction
             * @enum {string}
             */
            phaseType: "introduction" | "discussion" | "investigation" | "voting" | "reveal";
            /**
             * @description フェーズの説明
             * @example 事件の概要と各自の立場を確認
             */
            description: string;
            /**
             * @description 全プレイヤーに公開される情報
             * @example 被害者：サミュエル・ゴールドスタイン（65歳）...
             */
            publicText: string;
            /**
             * @description このプレイヤーだけに表示される情報
             * @example 【あなたの役割】
             *     名前: アレックス・クロフォード...
             */
            privateText: string;
            /**
             * @description このプレイヤーが実行可能なアクション
             * @example [
             *       "advance_phase"
             *     ]
             */
            availableActions: string[];
        };
        VoteRequest: {
            /**
             * @description 投票対象のプレイヤーID
             * @example 660e8400-e29b-41d4-a716-446655440002
             */
            targetPlayerId: string;
        };
        ResultResponse: {
            /**
             * @description 事件の真相
             * @example 犯人はアレックス・クロフォードである。動機は...
             */
            truth: string;
            /**
             * @description 最も票を集めたプレイヤーのID
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            winnerId: string;
            /**
             * @description 最も票を集めたプレイヤーの名前
             * @example アレックス・クロフォード
             */
            winnerName: string;
            /**
             * @description プレイヤーIDごとの得票数
             * @example {
             *       "660e8400-e29b-41d4-a716-446655440001": 2,
             *       "660e8400-e29b-41d4-a716-446655440002": 1
             *     }
             */
            votingResult: {
                [key: string]: number;
            };
            /**
             * @description プレイヤーIDと名前のマッピング
             * @example {
             *       "660e8400-e29b-41d4-a716-446655440001": "アレックス・クロフォード",
             *       "660e8400-e29b-41d4-a716-446655440002": "エミリー・ハートウェル"
             *     }
             */
            playerNames: {
                [key: string]: string;
            };
        };
        SuccessResponse: {
            /**
             * @description 成功メッセージ
             * @example phase advanced successfully
             */
            message: string;
        };
        ErrorResponse: {
            /**
             * @description エラーメッセージ
             * @example session not found
             */
            message: string;
        };
    };
    responses: never;
    parameters: {
        /**
         * @description セッションID
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        SessionIdParam: string;
        /**
         * @description プレイヤーID
         * @example 660e8400-e29b-41d4-a716-446655440001
         */
        PlayerIdHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description セッションが正常に作成された */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
            /** @description リクエストが不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPhase: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description プレイヤーID
                 * @example 660e8400-e29b-41d4-a716-446655440001
                 */
                "X-Player-Id": components["parameters"]["PlayerIdHeader"];
            };
            path: {
                /**
                 * @description セッションID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                sessionId: components["parameters"]["SessionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フェーズ情報を取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseResponse"];
                };
            };
            /** @description リクエストが不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description セッションが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    advancePhase: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description プレイヤーID
                 * @example 660e8400-e29b-41d4-a716-446655440001
                 */
                "X-Player-Id": components["parameters"]["PlayerIdHeader"];
            };
            path: {
                /**
                 * @description セッションID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                sessionId: components["parameters"]["SessionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フェーズを進めることに成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description リクエストが不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description オーナー以外は実行不可 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description セッションが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    vote: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description プレイヤーID
                 * @example 660e8400-e29b-41d4-a716-446655440001
                 */
                "X-Player-Id": components["parameters"]["PlayerIdHeader"];
            };
            path: {
                /**
                 * @description セッションID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                sessionId: components["parameters"]["SessionIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description 投票成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description リクエストが不正または既に投票済み */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description セッションが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description セッションID
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                sessionId: components["parameters"]["SessionIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 結果取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
            /** @description ゲームがまだ終了していない */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description セッションが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
